### ISSUE TITLE
Azure AD API deprecated => Migration to Graph API

### ISSUE THREAD

**Issue by jahrsensetence** [TheNetworg/oauth2-azure#216]
Hello,

we were informed that Microsoft is phasing out the Azure AD API (https://learn.microsoft.com/en-us/graph/migrate-azure-ad-graph-overview). Our application uses this package "in the default configuration", therefore, we do make requests to the deprecated API endpoint because:

https://github.com/TheNetworg/oauth2-azure/blob/master/src/Provider/Azure.php => Line 60

```
    public $urlAPI = 'https://graph.windows.net/';
```

Can I just change this URI? Will everything break? :)

Thanks,

Ralf

**Comment by Zhortein** [comment]
Hello,

I ran into the same issue with my Symfony application using this bundle together with the knpuniversity/oauth2-client-bundle. I fixed it by updating my configuration in config/packages/knpu_oauth2_client.yaml as follows:

```yaml
knpu_oauth2_client:
    clients:
        # Configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        
        # This will create a service "knpu.oauth2.client.azure" (an instance of KnpU\OAuth2ClientBundle\Client\Provider\AzureClient).
        # Make sure to run: composer require thenetworg/oauth2-azure
        azure:
            # Must be "azure" - it activates that type!
            type: azure
            # Set these environment variables in your .env files
            client_id: '%env(OAUTH_AZURE_CLIENT_ID)%'
            client_secret: '%env(OAUTH_AZURE_CLIENT_SECRET)%'
            tenant: '%env(OAUTH_AZURE_TENANT_ID)%'
            # The route name you'll create for redirection
            redirect_route: security.microsoft.azure.check
            redirect_params: {}
            # Whether to check the OAuth2 "state": defaults to true
            use_state: true
            scope:
                - 'offline_access'
                - 'openid'
                - 'email'
                - 'profile'
                - 'User.Read'
            url_api: 'https://graph.windows.com/'
            default_end_point_version: '2.0'

```

After making this change, the connection works perfectly for me.

I hope this workaround helps you resolve your issue without waiting for a bundle update.

Zhortein

**Comment by temp** [comment]
is graph.windows.com correct? shouldn't it be graph.microsoft.com? i thought the whole windows-graph-api was deprecated.

**Comment by Zhortein** [comment]
I've found this value on https://learn.microsoft.com/en-us/graph/migrate-azure-ad-graph-request-differences

**Comment by temp** [comment]
searching for windows.com shows no hit on this page?

**Comment by temp** [comment]
and https://graph.windows.com/ doesn't seem to resolve...

**Comment by Zhortein** [comment]
Sorry, I must have gone too fast in pasting the patch. You must indicate "https://graph.microsoft.com", the other URL was a previous test, which failed. The connection works for me.

**Comment by stephanwentz** [comment]
Just for completeness, I got it working with this config:

```
knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        azure:
            type: azure
            client_id: '%env(OAUTH_AZURE_ID)%'
            client_secret: '%env(OAUTH_AZURE_SECRET)%'
            redirect_route: my_redirect_route
            redirect_params: {}
            tenant: '%env(OAUTH_AZURE_TENANT_ID)%'
            url_api: 'https://graph.microsoft.com/'
```
